# Generated by Django 5.2 on 2025-05-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.CharField(default="(UNKNOWN)", max_length=200),
            preserve_default=False,
        ),
    ]
